dist: xenial
language: python
python:
  - '3.7'
sudo: false
cache:
  - pip
before_install:
  - pip3 install -r requirements.txt
install:
  - export PYTHONIOENCODING=UTF8
before_script:
  - pip3 install -e .
script:
  - nodejsscan -v
  - python tests.py
